### ISSUE TITLE
Whoogle config not sticking

### ISSUE THREAD

**Issue by bruvv** [bruvv/hassio-addons-1#20]
@alexbelgium hopefully you might be able to help me on this one. I rewrote the whoogle config file to include all the variables. But since I am still learning the home assisatant addons way of working I am not sure now why Whoogle isn't sticking. Could you help?
https://github.com/bruvv/hassio-addons-1/blob/whoogle-fix/whoogle/config.json

**Comment by alexbelgium** [comment]
Hi, that's normal you need to export them as env variable. Curernly I had avoided this and recommended people to configure variables through the config.yaml file. However, to make it stick the way you want, just copy this file in the /scripts folder : https://raw.githubusercontent.com/alexbelgium/hassio-addons/master/fireflyiii/rootfs/scripts/00-global_var.sh

This will take all addon options and export them as variables. It should work. Please avoid modifying this script through as it is one I treat a a module : single script used in all relevant addons for a single purpose (in this case, export all addons variables as env variables) :)

**Comment by bruvv** [comment]
Perfect thanks will test! I modified it a bit to fix https://github.com/koalaman/shellcheck/wiki/SC2163 and https://github.com/koalaman/shellcheck/wiki/SC2068 good tip to use with VSCODE: https://marketplace.visualstudio.com/items?itemName=timonwong.shellcheck

**Comment by alexbelgium** [comment]
Thanks I'll look at it!
